import Image from "next/image";
import { Mail, MapPin, Phone } from "lucide-react";
import { CTASection } from "@/components/cta-section";
import { PageHero } from "@/components/page-hero";
import { placeholderAssets } from "@/data/placeholders";
import { site } from "@/data/site";
import { createPageMetadata } from "@/lib/metadata";
export const metadata = createPageMetadata({ title: "સંપર્ક | શબરીધામ શાળા સંકુલ", description: "શબરીધામ શાળા, વ્યારા માટે સંપર્ક અને પૂછપરછ માહિતી.", path: "/contact" });
export default function ContactPage(){return <><PageHero variant="shabridham-ref" content={{eyebrow:"સંપર્ક",title:"તમારી વિનંતીમાં મદદ કરીએ",description:"એડમિશન, શાળા મુલાકાત માર્ગદર્શન, ક્લાસ ઉપલબ્ધતા અને અધિકૃત માહિતી પુષ્ટિ માટે સંપર્ક કરો.",imageSrc:placeholderAssets.contact,imageAlt:"પ્લેસહોલ્ડર: સંપર્ક",primaryCta:{label:"એડમિશન",href:"/admissions"},secondaryCta:{label:"મુખ્ય પૃષ્ઠ",href:"/"}}}/><section className="panel section-pad section-gap"><div className="grid gap-5 md:grid-cols-3"><article className="course-card p-5"><MapPin/><h2 className="mt-4 text-2xl font-black">સરનામું</h2><p className="body-copy mt-2 text-sm">{site.address}</p></article><article className="course-card p-5"><Phone/><h2 className="mt-4 text-2xl font-black">ફોન</h2>{site.phones.map((p)=><p className="body-copy mt-2 text-sm" key={p}>{p}</p>)}</article><article className="course-card p-5"><Mail/><h2 className="mt-4 text-2xl font-black">ઇમેઇલ</h2><p className="body-copy mt-2 text-sm">{site.email}</p></article></div></section><section className="panel section-pad section-gap"><div className="grid gap-8 lg:grid-cols-[1fr_.9fr]"><form className="grid gap-4" action="#"><h2 className="title-lg">સંદેશ મોકલો</h2><input className="rounded-2xl border-2 border-black bg-white px-4 py-3" placeholder="વાલીનું નામ"/><input className="rounded-2xl border-2 border-black bg-white px-4 py-3" placeholder="ફોન નંબર"/><input className="rounded-2xl border-2 border-black bg-white px-4 py-3" placeholder="ઇમેઇલ"/><textarea className="min-h-32 rounded-2xl border-2 border-black bg-white px-4 py-3" placeholder="સંદેશ"/><button type="button" className="btn-primary w-fit">વિનંતી મોકલો</button></form><div><Image src={placeholderAssets.contact} alt="પ્લેસહોલ્ડર: નકશો દ્રશ્ય" width={720} height={520} className="illo-card"/><div className="sticker mt-5 bg-[var(--yellow)]"><span className="badge">સમય</span><p className="body-copy mt-3">કચેરી સમય અને નકશો પિન પુષ્ટિ બાકી. મુલાકાત પહેલાં કૃપા કરીને કોલ કરો.</p></div></div></div></section><CTASection variant="shabridham-ref" title="મુલાકાત પહેલાં શાળા વિગતો પુષ્ટિ કરો." description="આ પૃષ્ઠ અધિકૃત સંપર્કો, નકશો લિંક અને વાસ્તવિક મુલાકાત સમય માટે તૈયાર છે." primary={{label:"એડમિશન",href:"/admissions"}} secondary={{label:"YouTube",href:"https://www.youtube.com/channel/UCdlhAdOGNC-9eWqLlllgvHQ"}}/></>}
