import Image from "next/image";
import { Mail, MapPin, Phone } from "lucide-react";
import { CTASection } from "@/components/cta-section";
import { PageHero } from "@/components/page-hero";
import { placeholderAssets } from "@/data/placeholders";
import { site } from "@/data/site";
import { createPageMetadata } from "@/lib/metadata";
export const metadata = createPageMetadata({ title: "Contact | Shabridham Shala", description: "Contact Shabridham Shala, Vyara.", path: "/contact" });
export default function ContactPage(){return <><PageHero variant="shabridham-ref" content={{eyebrow:"Contact",title:"Let us help with your inquiry",description:"Reach out for admissions, school visit guidance, class availability, and official information confirmation.",imageSrc:placeholderAssets.contact,imageAlt:"Placeholder contact",primaryCta:{label:"Admissions",href:"/admissions"},secondaryCta:{label:"Home",href:"/"}}}/><section className="panel section-pad section-gap"><div className="grid gap-5 md:grid-cols-3"><article className="course-card p-5"><MapPin/><h2 className="mt-4 text-2xl font-black">Address</h2><p className="body-copy mt-2 text-sm">{site.address}</p></article><article className="course-card p-5"><Phone/><h2 className="mt-4 text-2xl font-black">Phone</h2>{site.phones.map((p)=><p className="body-copy mt-2 text-sm" key={p}>{p}</p>)}</article><article className="course-card p-5"><Mail/><h2 className="mt-4 text-2xl font-black">Email</h2><p className="body-copy mt-2 text-sm">{site.email}</p></article></div></section><section className="panel section-pad section-gap"><div className="grid gap-8 lg:grid-cols-[1fr_.9fr]"><form className="grid gap-4" action="#"><h2 className="title-lg">Send a message</h2><input className="rounded-2xl border-2 border-black bg-white px-4 py-3" placeholder="Parent Name"/><input className="rounded-2xl border-2 border-black bg-white px-4 py-3" placeholder="Phone"/><input className="rounded-2xl border-2 border-black bg-white px-4 py-3" placeholder="Email"/><textarea className="min-h-32 rounded-2xl border-2 border-black bg-white px-4 py-3" placeholder="Message"/><button type="button" className="btn-primary w-fit">Submit Inquiry</button></form><div><Image src={placeholderAssets.contact} alt="Placeholder map visual" width={720} height={520} className="illo-card"/><div className="sticker mt-5 bg-[var(--yellow)]"><span className="badge">Timing</span><p className="body-copy mt-3">Office timings and map pin to be confirmed. Please call before visiting.</p></div></div></div></section><CTASection variant="shabridham-ref" title="Confirm school details before visiting." description="This page is ready for official contacts, map link, and real visit timings." primary={{label:"Admissions",href:"/admissions"}} secondary={{label:"YouTube",href:"https://www.youtube.com/channel/UCdlhAdOGNC-9eWqLlllgvHQ"}}/></>}
