import Image from "next/image";
import Link from "next/link";
import { CTASection } from "@/components/cta-section";
import { PageHero } from "@/components/page-hero";
import { placeholderAssets } from "@/data/placeholders";
import { createPageMetadata } from "@/lib/metadata";

export const metadata = createPageMetadata({ title: "મુખ્ય પૃષ્ઠ | Shabridham Shala", description: "શબરીધામ શાળા, વ્યારા માટે લર્નિફાય-શૈલીનો શાળા વેબસાઇટ કૉન્સેપ્ટ.", path: "/" });
const courses = [["ગુજરાતી આધાર", "વાંચન, લખાણ, અભિવ્યક્તિ", "bg-[var(--purple)]", placeholderAssets.classroom], ["રાજ્ય બોર્ડ તૈયારી", "વર્ગખંડ ટેવો અને મૂલ્યાંકન", "bg-[var(--yellow)]", placeholderAssets.reading], ["સ્માર્ટ અભ્યાસ કૌશલ્ય", "ડિજિટલ આધાર અને ક્વિઝ", "bg-[var(--soft)]", placeholderAssets.computer], ["પ્રવૃત્તિઓ", "સાંસ્કૃતિક, રમતગમત, ભાગીદારી", "bg-black text-white", placeholderAssets.sports]];
export default function HomePage() {
  return <>
    <PageHero variant="shabridham-ref" content={{ eyebrow: "શબરીધામ શાળા", title: "વ્યારા માં તમારો અભ્યાસ માર્ગ શોધો", description: "શબરીધામ શાળા માટે રમૂજી અને પેરેન્ટ-ફ્રેન્ડલી વેબસાઇટ કૉન્સેપ્ટ: ગુજરાતી શીખણ, શાળા-પરિસર સંદર્ભ, પ્રવૃત્તિઓ અને સ્માર્ટ અભ્યાસ આત્મવિશ્વાસ પર આધારિત.", imageSrc: placeholderAssets.hero, imageAlt: "પ્લેસહોલ્ડર: વિદ્યાર્થીઓ અભ્યાસ કરે છે", primaryCta: { label: "Admissions માહિતી", href: "/admissions" }, secondaryCta: { label: "શાળાની કહાણી જુઓ", href: "/about" } }} />
    <section className="panel section-pad section-gap"><div className="grid gap-8 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><h2 className="title-lg">તમારી <span className="highlight">જ્ઞાન</span> યાત્રા આગળ વધારો</h2><p className="body-copy">જાહેર માહિતી મર્યાદિત હોવાથી, આ સાઇટ વ્યારા/શબરીધામ સંબંધિત ચકાસી શકાય તેવા સંકેતો સાથે સંપાદિત કરી શકાય તેવું શાળા-સલામત લખાણ ઉપયોગ કરે છે. શબરીધામ વિસ્તારમાં શાળા સંદર્ભ અને Shree M.P. Patel Madhy Shala જેવી નોંધોને સાવચેતીપૂર્વક દર્શાવવામાં આવે છે.</p></div><div className="mt-8 flex flex-wrap gap-3"><span className="chip chip-active">નવા માર્ગ</span><span className="chip">ભલામણ</span><span className="chip">ઉપયોગી</span></div><div className="mt-8 grid gap-5 md:grid-cols-4">{courses.map(([title,text,color,img])=><article className="course-card" key={title}><div className={`course-img ${color}`}><Image src={img} alt={`પ્લેસહોલ્ડર: ${title}`} width={420} height={300} className="h-full w-full object-cover mix-blend-multiply" /></div><div className="p-3"><span className="badge">શાળા</span><h3 className="mt-3 text-2xl font-black">{title}</h3><p className="body-copy mt-2 text-sm">{text}</p><Link href="/academics" className="btn-primary mt-4 w-full">વિગતો જુઓ</Link></div></article>)}</div></section>
    <section className="panel section-pad section-gap bg-[var(--yellow)]"><div className="grid gap-8 lg:grid-cols-2 lg:items-center"><div><h2 className="title-lg">શાળા માટે તૈયાર <span className="text-white">કૌશલ્ય</span> વધારો</h2><p className="body-copy mt-5">વાંચન આત્મવિશ્વાસથી લઈને કમ્પ્યુટર આધાર સુધી, અંતિમ સાઇટ પેરેન્ટ્સ માટે માહિતી અને Admissions માર્ગદર્શનનું પકડેલું હબ બની શકે છે.</p><Link href="/ai-learning" className="btn-primary btn-dark mt-7">હમણાં શરૂ કરો</Link></div><Image src={placeholderAssets.illustrationA} alt="પ્લેસહોલ્ડર: શીખણ દ્રશ્ય" width={760} height={520} className="illo-card" /></div></section>
    <section className="panel section-pad section-gap"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><h2 className="title-lg">મુખ્ય <span className="highlight">વિષયો</span> શોધો</h2><div><div className="flex flex-wrap gap-3"><span className="chip chip-active">ગુજરાતી</span><span className="chip">ગણિત</span><span className="chip">વિજ્ઞાન</span><span className="chip">કમ્પ્યુટર</span><span className="chip">પ્રવૃત્તિઓ</span></div><p className="body-copy mt-10 max-w-xl">ગુજરાતી-માધ્યમ સ્પષ્ટતા, શિસ્ત, ડિજિટલ અનુભવ અથવા પ્રવૃત્તિ આધારિત વિકાસ માટે શોધતા પરિવારોને ધ્યાનમાં રાખીને લખાણ સરળ અને સ્કૅનેબલ રાખ્યું છે.</p></div></div></section>
    <CTASection variant="shabridham-ref" title="Admissions વિશે પૂછવા તૈયાર છો?" description="સંપર્ક મૂલ્યો અધિકૃત પુષ્ટિ થાય ત્યાં સુધી પ્લેસહોલ્ડર છે, પરંતુ પેરેન્ટ પૂછપરછ માટે પ્રવાહ તૈયાર છે." primary={{ label: "Admissions પૂછપરછ", href: "/admissions" }} secondary={{ label: "સંપર્ક", href: "/contact" }} />
  </>;
}
