import Image from "next/image";
import Link from "next/link";
import { CTASection } from "@/components/cta-section";
import { PageHero } from "@/components/page-hero";
import { placeholderAssets } from "@/data/placeholders";
import { createPageMetadata } from "@/lib/metadata";

export const metadata = createPageMetadata({ title: "Home | Shabridham Shala", description: "Learnify-style school website for Shabridham Shala, Vyara.", path: "/" });
const courses = [["Gujarati Foundation", "Reading, writing, expression", "bg-[var(--purple)]", placeholderAssets.classroom], ["State Board Readiness", "Classroom habits and assessment", "bg-[var(--yellow)]", placeholderAssets.reading], ["Smart Study Skills", "Digital basics and quizzes", "bg-[var(--soft)]", placeholderAssets.computer], ["Activities", "Culture, sports, participation", "bg-black text-white", placeholderAssets.sports]];
export default function HomePage() {
  return <>
    <PageHero variant="shabridham-ref" content={{ eyebrow: "Shabridham Shala", title: "Find your learning path in Vyara", description: "A playful, parent-friendly school website concept for Shabridham Shala, built around Gujarati learning, school-complex context, activities, and smart study confidence.", imageSrc: placeholderAssets.hero, imageAlt: "Placeholder students learning", primaryCta: { label: "Find admission", href: "/admissions" }, secondaryCta: { label: "View school story", href: "/about" } }} />
    <section className="panel section-pad section-gap"><div className="grid gap-8 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><h2 className="title-lg">Take your <span className="highlight">knowledge</span> a step further</h2><p className="body-copy">Public information is limited, so this site uses verified Vyara/Shabridham signals with editable school-safe content. It references the Shabridham school area and Shree M.P. Patel Madhy Shala context carefully.</p></div><div className="mt-8 flex flex-wrap gap-3"><span className="chip chip-active">New learning paths</span><span className="chip">Recommended</span><span className="chip">Most helpful</span></div><div className="mt-8 grid gap-5 md:grid-cols-4">{courses.map(([title,text,color,img])=><article className="course-card" key={title}><div className={`course-img ${color}`}><Image src={img} alt={`Placeholder ${title}`} width={420} height={300} className="h-full w-full object-cover mix-blend-multiply" /></div><div className="p-3"><span className="badge">School</span><h3 className="mt-3 text-2xl font-black">{title}</h3><p className="body-copy mt-2 text-sm">{text}</p><Link href="/academics" className="btn-primary mt-4 w-full">More details</Link></div></article>)}</div></section>
    <section className="panel section-pad section-gap bg-[var(--yellow)]"><div className="grid gap-8 lg:grid-cols-2 lg:items-center"><div><h2 className="title-lg">Upgrade your <span className="text-white">skills</span> with school-ready learning</h2><p className="body-copy mt-5">From reading confidence to computer basics, the final site can become a polished parent-facing admissions and information hub.</p><Link href="/ai-learning" className="btn-primary btn-dark mt-7">Start now</Link></div><Image src={placeholderAssets.illustrationA} alt="Placeholder learning visual" width={760} height={520} className="illo-card" /></div></section>
    <section className="panel section-pad section-gap"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><h2 className="title-lg">Explore top <span className="highlight">subjects</span></h2><div><div className="flex flex-wrap gap-3"><span className="chip chip-active">Gujarati</span><span className="chip">Maths</span><span className="chip">Science</span><span className="chip">Computer</span><span className="chip">Activities</span></div><p className="body-copy mt-10 max-w-xl">Whether families are looking for Gujarati-medium clarity, discipline, digital exposure, or activity-rich growth, the site keeps content friendly and easy to scan.</p></div></div></section>
    <CTASection variant="shabridham-ref" title="Ready to ask about admissions?" description="Contact values are placeholders until official confirmation, but the flow is ready for parent inquiries." primary={{ label: "Admission Inquiry", href: "/admissions" }} secondary={{ label: "Contact", href: "/contact" }} />
  </>;
}
